# Site settings
title: RealityTech
subtitle: Spatial Augmented Reality and interactive projection.
email: laviole@rea.lity.tech
description: RealityTech's website, products an news.
baseurl: "/test" # the subpath of your site, e.g. /blog
# url: "http://rea.lity.tech" # the base hostname & protocol for your site
author: RealityTech SASU
street_address: 26 rue Fernand Marin
city: Bordeaux
state: Aquitaine
zip_code: 33000
country: France
phone: (+33) 7 50 38 73 (sept sept)

# Social settings
500px_url:
facebook_url: https://www.facebook.com/reality.over.tech
github_url: https://github.com/Rea-lity-Tech
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/company/10567261/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/rea_lity_tech

sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown
